# lightning.pytorch==2.2.1
seed_everything: true
trainer:
  accelerator: auto
  strategy: ddp
  devices: 2
  num_nodes: 1
  precision: 32
  logger:
    class_path: lightning.pytorch.loggers.WandbLogger
    init_args:
      project: phalar
  callbacks:
    - class_path: lightning.pytorch.callbacks.ModelCheckpoint
      init_args:
        monitor: valid_accuracy
        save_top_k: 5
        mode: max
        filename: checkpoint-{epoch}-{valid_accuracy:.4f}
  fast_dev_run: false
  max_epochs: 500
  min_epochs: null
  max_steps: -1
  min_steps: null
  max_time: null
  limit_train_batches: null
  limit_val_batches: null
  limit_test_batches: null
  limit_predict_batches: null
  overfit_batches: 0.0
  val_check_interval: null
  check_val_every_n_epoch: 1
  num_sanity_val_steps: 0
  log_every_n_steps: null
  enable_checkpointing: null
  enable_progress_bar: true
  enable_model_summary: null
  accumulate_grad_batches: 1
  gradient_clip_val: null
  gradient_clip_algorithm: null
  deterministic: true
  benchmark: null
  inference_mode: true
  use_distributed_sampler: true
  profiler: null
  detect_anomaly: false
  barebones: false
  plugins: null
  sync_batchnorm: true
  reload_dataloaders_every_n_epochs: 0
  default_root_dir: /path/to/checkpoints
data:
  root_dir: /path/to/datasets
  dataset: MIXED
  batch_size: 64
  chunk_duration_test: 5
  target_sample_rate: 16000
  generate_submixtures: true
  feature_extractor_type: RAW_WAVEFORM # STFT/CQT/MEL/HPSS_SPECTROGRAM | RAW_WAVEFORM
  feature_extraction_time: ONLINE
ckpt_path: null
